### ISSUE TITLE
Include Instagram and LinkedIn Links In Signature

### ISSUE THREAD

**Issue by harshkhandeparkar** [kossiitkgp/mailing-scripts#6]
See https://github.com/kossiitkgp/mailing-scripts/blob/main/templates/signature

**Comment by ViciousEagle03** [comment]
Is this issue still relevant to the code base? if yes, can you assign me this issue?

**Comment by jameel-azad** [comment]
@harshkhandeparkar  If this is still an issue, can you please assign it to me for kwoc'23?

**Comment by proffapt** [comment]
@jameel-azad you can start working on it
